!insertmacro MUI_DEFAULT MUI_TEXT_COLOR FFFFFF
!insertmacro MUI_DEFAULT MUI_BGCOLOR 3dab66
!insertmacro MUI_DEFAULT UMUI_TEXT_LIGHTCOLOR FF00FF
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTFRONTCOLOR 8ba48c
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTBACKCOLOR eef3ee
!insertmacro MUI_DEFAULT UMUI_LEFTIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\cleargreen\LeftBranding.bmp"
!insertmacro MUI_DEFAULT UMUI_HEADERIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\cleargreen\Header.bmp"
!insertmacro MUI_DEFAULT UMUI_BOTTOMIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\cleargreen\BtmImg.bmp"
!insertmacro MUI_DEFAULT MUI_ICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\Icon.ico"
!insertmacro MUI_DEFAULT MUI_UNICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\UnIcon.ico"