!insertmacro MUI_DEFAULT MUI_TEXT_COLOR FFFFFF
!insertmacro MUI_DEFAULT MUI_BGCOLOR 7B7B7B
!insertmacro MUI_DEFAULT UMUI_TEXT_LIGHTCOLOR FFFF00
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTFRONTCOLOR 8e8e8e
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTBACKCOLOR ececec
!insertmacro MUI_DEFAULT UMUI_LEFTIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\gray\LeftBranding.bmp"
!insertmacro MUI_DEFAULT UMUI_HEADERIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\gray\Header.bmp"
!insertmacro MUI_DEFAULT UMUI_BOTTOMIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\gray\BtmImg.bmp"
!insertmacro MUI_DEFAULT MUI_ICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\Icon.ico"
!insertmacro MUI_DEFAULT MUI_UNICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\UnIcon.ico"