!insertmacro MUI_DEFAULT MUI_TEXT_COLOR b5d3ef
!insertmacro MUI_DEFAULT MUI_BGCOLOR 52697b
!insertmacro MUI_DEFAULT UMUI_TEXT_LIGHTCOLOR b5d300
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTFRONTCOLOR 5a616b
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTBACKCOLOR 7b868c
!insertmacro MUI_DEFAULT UMUI_LEFTIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\green\LeftBranding.bmp"
!insertmacro MUI_DEFAULT UMUI_HEADERIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\green\Header.bmp"
!insertmacro MUI_DEFAULT UMUI_BOTTOMIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\green\BtmImg.bmp"
!insertmacro MUI_DEFAULT MUI_ICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\Icon.ico"
!insertmacro MUI_DEFAULT MUI_UNICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\UnIcon.ico"