!insertmacro MUI_DEFAULT MUI_TEXT_COLOR FFFFFF
!insertmacro MUI_DEFAULT MUI_BGCOLOR 663dab
!insertmacro MUI_DEFAULT UMUI_TEXT_LIGHTCOLOR 00FFFF
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTFRONTCOLOR 8c8ba4
!insertmacro MUI_DEFAULT UMUI_BRANDINGTEXTBACKCOLOR eeeef3
!insertmacro MUI_DEFAULT UMUI_LEFTIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\purple\LeftBranding.bmp"
!insertmacro MUI_DEFAULT UMUI_HEADERIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\purple\Header.bmp"
!insertmacro MUI_DEFAULT UMUI_BOTTOMIMAGE_BMP "${NSISDIR}\Contrib\UltraModernUI\Skins\purple\BtmImg.bmp"
!insertmacro MUI_DEFAULT MUI_ICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\Icon.ico"
!insertmacro MUI_DEFAULT MUI_UNICON "${NSISDIR}\Contrib\Graphics\UltraModernUI\UnIcon.ico"