#!/bin/bash

DIRS=($(ls -d /home/*/))

for dir in ${DIRS[*]}
do
	mkdir -p $dir/Desktops/Desktop1/
    cp /usr/share/applications/SkyHobbitAOMS.desktop  $dir/Desktops/Desktop1/SkyHobbitAOMS.desktop
    cp /usr/share/applications/SkyHobbitAOMS.desktop  /root/Desktops/Desktop1/SkyHobbitAOMS.desktop
done 

ldconfig
