# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "NMake Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "ZIP")
SET(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp$;\\.#;/#")
SET(CPACK_INSTALLED_DIRECTORIES "F:/Projects/Qt/Zaviruha2/zaviruha_r;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "C:/Program Files/ZaviruhaR")
SET(CPACK_MODULE_PATH "F:/Projects/Qt/Zaviruha2/zaviruha_r/cmake;F:/Projects/Qt/Zaviruha2/zaviruha_r/cmake/win32/")
SET(CPACK_NSIS_CREATE_ICONS_EXTRA "
CreateShortCut '$DESKTOP\\Завируха АРМ Р 5.0.0.lnk' '$INSTDIR\\ZaviruhaRView.exe'
")
SET(CPACK_NSIS_DELETE_ICONS_EXTRA "
Delete '$DESKTOP\\Завируха АРМ Р 5.0.0.lnk'
")
SET(CPACK_NSIS_DISPLAY_NAME "Завируха АРМ Р 5.0.0")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_ENABLE_REMOVE_INSTDIR_RECURSIVE "ON")
SET(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
SET(CPACK_NSIS_INSTALLED_ICON_NAME "ZaviruhaRView.exe")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "C:")
SET(CPACK_NSIS_MENU_LINKS "ZaviruhaRView.exe;Завируха АРМ Р 5.0.0;Zaviruha_instruction.docx;Документация")
SET(CPACK_NSIS_PACKAGE_NAME "Завируха АРМ Р 5.0.0")
SET(CPACK_OUTPUT_CONFIG_FILE "F:/Projects/Qt/Zaviruha2/zaviruha_r/build1/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Завируха АРМ Р 5.0.0")
SET(CPACK_PACKAGE_FILE_NAME "ZaviruhaR-5.0.0-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "STC\\ZaviruhaR-5.0.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ZaviruhaR 5.0")
SET(CPACK_PACKAGE_NAME "ZaviruhaR")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "STC")
SET(CPACK_PACKAGE_VERSION "5.0.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files (x86)/CMake/share/cmake-3.0/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp$;\\.#;/#")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "F:/Projects/Qt/Zaviruha2/zaviruha_r;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "F:/Projects/Qt/Zaviruha2/zaviruha_r/build1/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "ZaviruhaR-5.0.0-Source")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "win64")
SET(CPACK_TOPLEVEL_TAG "win64-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
